### PR TITLE
Resolve Sidebar issues

### PR DESCRIPTION
**Pull request by elsteelbrain**
Fixes: #172

### CODE REVIEW

**Comment by DavidWells** [comment]
Deploy preview ready!

Built with commit 4a59e06d0225893447289773a958ef891ce3449b

https://deploy-preview-199--serverless.netlify.com

**Comment by elsteelbrain** [comment]
@DavidWells please take look, so that, we can merge.

**Comment by DavidWells** [comment]
This breaks the blog sidebar when resizing.

We need the blog sidebar from master. See https://serverless.com/blog/things-i-learned-designing-developer-tools/ and resize. There is no issue on live site

blog bokren

**Comment by elsteelbrain** [comment]
@DavidWells Take a look now!

**Pull request merged**
