### PR TITLE
update jobs page

### PR DESCRIPTION
**Pull request by worldsoup**
several changes here
- include link to new jobs listings page
- include company values
- update perks to be more accurate

### CODE REVIEW

**Comment by worldsoup** [comment]
@DavidWells can you please update nav to point to this page? Can we also make this page more visible by making it a top level item? or maybe including in footer?

**Comment by DavidWells** [comment]
Deploy preview ready!

Built with commit 7f996b35d7ab483fa26e9178357fad0f8a11fe29

https://deploy-preview-93--serverless.netlify.com

**Comment by worldsoup** [comment]
hmm this doesn't look very good, is there an easy way to make the values in to a 2 column view? might help break it up and make the page shorter @DavidWells

**Comment by DavidWells** [comment]
This is out dated / old?

**Comment by worldsoup** [comment]
ya I'll kill it

**Pull request closed without merging**
