### PR TITLE
add better fit for trek10 partner logo

### PR DESCRIPTION
**Pull request by shortjared**

### CODE REVIEW

**Comment by DavidWells** [comment]
Deploy preview ready!

Built with commit 40c349f7be116468a441ca85661982d010cc7c82

https://deploy-preview-100--serverless.netlify.com

**Comment by shortjared** [comment]
oh man. deploy preview. that is handy... makes my screenshot useless but you can still have it because.

image

**Comment by worldsoup** [comment]
lgtm!

**Comment by shortjared** [comment]
❤️  thank you, but you beat me to adding in the actual right logo. oops.

**Pull request merged**
