### PR TITLE
New design

### PR DESCRIPTION
**Pull request by steelbrain**
Not to be merged yet. Just to track progress and collect feedback.

### CODE REVIEW

**Comment by DavidWells** [comment]
Deploy preview ready!

Built with commit 397fcb3a646cc458cf304beb624e012cb4939b02

https://deploy-preview-113--serverless.netlify.com

**Comment by DavidWells** [comment]
Can we rename the font files to human readable names? :)

Also if you need to add any large image assets, lets toss those up into S3 to keep those out of the git history. Toss them up on GitHub cdn or something if you need to have a live URL or send them over and we can get them into s3

**Comment by steelbrain** [comment]
@DavidWells I just changed the font file names. And will keep that in mind about large files 😉

**Comment by asgs** [comment]
Hello! Please consider the below commits as well and modify as necessary.

https://github.com/serverless/site/pull/119
https://github.com/serverless/site/pull/118

**Pull request merged**
