### PR TITLE
Jobs page

### PR DESCRIPTION
**Pull request by stefanroex**
This PR isn't ready yet, just the start of the new jobs page. I'll update the description as soon as its ready.

### CODE REVIEW

**Comment by DavidWells** [comment]
Deploy preview ready!

Built with commit 4e1f9f2c31c2336a96d29ddc62ce82abb5a386ce

https://deploy-preview-96--serverless.netlify.com

**Comment by DavidWells** [comment]
@stefanroex Looks good!

holler if you have any questions about the site setup

**Comment by worldsoup** [comment]
@stefanroex good start! can we just include the job title/location/team and leave off the description?

**Comment by DavidWells** [comment]
@stefanroex looking good.

One quick note: We don't want to add any image assets to the site repo. Instead, we toss those up into the CDN.

here are links to replace the images
https://s3-us-west-2.amazonaws.com/assets.site.serverless.com/images/jobs_heading.jpg
https://s3-us-west-2.amazonaws.com/assets.site.serverless.com/images/jobs_images.jpg

Can you remove those images from the PR?

Many thanks!

**Comment by stefanroex** [comment]
@DavidWells Thanks! I'll probably update or change some pictures, so I'll ping you then!

**Comment by stefanroex** [comment]
@DavidWells I've just pushed a new commit with some new images, but please don't upload them to the CDN yet since the images will probably be changed later this week.

Is it ok with you if I ping you when the PR is done? I could rebase and squash everything into a single commit after you've uploaded the images so they won't be visible in git.

**Comment by DavidWells** [comment]
Hey @stefanroex can you `git obliterate` the images and just add them here to githubs CDN?

I want to make sure all binaries are not in the git history to keep things tiny.

**Comment by worldsoup** [comment]
@stefanroex this looks good to me! as soon as @DavidWells gives the thumbs up lets merge it in

**Comment by worldsoup** [comment]
@stefanroex can you try removing the yellow filter on the image and changing the text to white?

**Comment by stefanroex** [comment]
@worldsoup I've removed the yellow filter and added some (simple) icons for the benefits and perks. It's good to go I think :-).

@DavidWells I've removed the assets and squashed the commits. Could you upload these assets to the CDN? [jobs-page-assets.zip](https://github.com/serverless/site/files/903561/jobs-page-assets.zip)

**Comment by DavidWells** [comment]
Uploaded them to new folders matching the file names sent over:

https://s3-us-west-2.amazonaws.com/assets.site.serverless.com/jobs/images/jobs_heading.jpg
https://s3-us-west-2.amazonaws.com/assets.site.serverless.com/jobs/images/*

https://s3-us-west-2.amazonaws.com/assets.site.serverless.com/jobs/icons/perks-icon-1.svg
https://s3-us-west-2.amazonaws.com/assets.site.serverless.com/jobs/icons/*

**Comment by stefanroex** [comment]
@DavidWells Wow, that was quick 👍. I've updated the URL's. (cc: @worldsoup).

**Comment by DavidWells** [comment]
I'm ⚡️

Nick mentioned you had some ideas on refactoring the site. I'd be curious to hear your thoughts on this. I'm a fan of your code =)

**Comment by worldsoup** [comment]
@DavidWells can I go ahead and merge this?

**Pull request merged**
