### PR TITLE
Clone Latest Release on Post Install (latest docs)

### PR DESCRIPTION
**Pull request by mattiasnixell**
This is a proposal to fix the issue with serverless.com docs using master branch instead of latest release as noted in https://forum.serverless.com/t/latest-version-documentation/4955.

There's an alternative proposal by @alexdebrie https://github.com/serverless/site/pull/178. However, instead of modifying the config object structure I just update the config repoBranch value. This doesn't break any scripts and makes the branch config consistent.

### CODE REVIEW

**Comment by DavidWells** [comment]
Deploy preview for *serverless* ready!

Built with commit c2d819507ad1d799fad163d8e2302ced001f1973

https://deploy-preview-290--serverless.netlify.com

**Comment by mattiasnixell** [comment]
What could be added is a local cache unique per endpoint to avoid multiple calls in case the sync request utility will be required in many places in future. However, I don't think that will happen very soon, so I'd recommend going with minimum code for now.

**Comment by mattiasnixell** [comment]
The update can be verified by comparing this document page:
https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
https://deploy-preview-290--serverless.netlify.com/framework/docs/providers/aws/guide/serverless.yml/

e.g. serverless.com has `apiName` from master, compared to netlify that doesn't (latest release).

**Comment by pdaryani** [comment]
closing because this feature has already been implemented in the following PR: https://github.com/serverless/site/pull/178

**Pull request closed without merging**
