### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by alexdebrie**

### CODE REVIEW

**Comment by pdaryani** [comment]
Thanks @alexdebrie 🙌

**Comment by worldsoup** [comment]
Your deploy preview is ready!

Built with commit 0ce7b6b0f6458fac33eee5d81414586769cc93ec

https://deploy-preview-484--serverless.netlify.com

**Comment by worldsoup** [comment]
Your deploy preview is ready!

Built with commit 0ce7b6b0f6458fac33eee5d81414586769cc93ec

https://deploy-preview-484--serverless.netlify.com

**Comment by worldsoup** [comment]
Your deploy preview is ready!

Built with commit 16a486ab4c84d7ea3db88d7a42afa61a2671d2ed

https://deploy-preview-484--serverless.netlify.com

**Pull request merged**
