### PR TITLE
New /partners page

### PR DESCRIPTION
**Pull request by pdaryani**

### CODE REVIEW

**Comment by worldsoup** [comment]
Your deploy preview is ready!

Built with commit 219aba5c9cd00f5f88b26684119fa30a0268e524

https://deploy-preview-384--serverless.netlify.com

**Comment by worldsoup** [comment]
@pdaryani how are determining the order here?

**Comment by pdaryani** [comment]
hi @worldsoup for now I just followed the order laid out by @carlosandrebp in Zeplin

please let me know if you have any recommendation regarding this

**Comment by carlosandrebp** [comment]
Hey @thomcrowe can you help us understand how the Partners were ordered?

**Comment by thomcrowe** [comment]
Hey @andrea-p, they were ordered by how they responded to my email. We can change the order up though.

**Comment by carlosandrebp** [comment]
@worldsoup do you have any thoughts about how this order should be?

**Comment by worldsoup** [comment]
Thom will be updating the order shortly...once that's updated we can go ahead and ship it.

**Comment by thomcrowe** [comment]
Let's go with this:

1. Trek10
2. Parallax
3. superluminar
4. Mode 2
5. Tech Magic
6. 99X Technology
7. Sinapsis
8. Kenzan

**Comment by pdaryani** [comment]
hey @thomcrowe, I've updated the order

**Pull request merged**
