### PR TITLE
Blog: Make newsletter input wider

### PR DESCRIPTION
**Pull request by elsteelbrain**

### CODE REVIEW

**Comment by DavidWells** [comment]
Deploy preview ready!

Built with commit e5a0cd09fe76d823d80772b31459a90b2fe1903f

https://deploy-preview-197--serverless.netlify.com

**Comment by DavidWells** [comment]
looks good need the button back on the left then its good to merge

image

**Comment by elsteelbrain** [comment]
Done

**Comment by DavidWells** [comment]
> need the button back on the left 

It's on the right now. Need it back on the left

**Comment by elsteelbrain** [comment]
I thought it looked better on the right but oh well.

**Pull request merged**
