### PR TITLE
Add serverless.com/cn Index

### PR DESCRIPTION
**Pull request by tongtingting**

### CODE REVIEW

**Comment by ac360** [comment]
Deploy preview for *serverless* processing.

Building with commit 408b6f3ba8976b7476d2a7651e00c329351914e7

https://app.netlify.com/sites/serverless/deploys/5e0b631546e996f4e5a17ab7

**Comment by canmengfly** [comment]
Hi, @pdaryani Thank you very much. The preview was successful. Can you help me change the jump in China? I don't know if it's the right thing to do.
https://github.com/tongtingting/site/pull/2/files
And when will this branch merge?

**Comment by pdaryani** [comment]
Hi @canmengfly the redirects look great, I'll merge them in!

PR is ready to be merged, just one quick question -- for the chinese tencent docs
- https://deploy-preview-517--serverless.netlify.com/cn/framework/docs/
- https://deploy-preview-517--serverless.netlify.com/cn/framework/docs/providers/tencent/cli-reference/create/

shall we:
#1 - restrict left navigation to be focused around Tencent: https://tinyurl.com/vlo6erj
#2 - have it as our normal sidebar menu with the only difference being Tencent items link to chinese version instead of English

Would be great to get your feedback on this

**Comment by canmengfly** [comment]
Hi Thank you very much for your reply, I think # 1 would be better. We need /cn to display all Chinese documents. This will help us better promote in China.

**Comment by pdaryani** [comment]
@canmengfly ok excellent, will make this live today itself then -- ping you as soon as I'm done :)

**Comment by pdaryani** [comment]
Hi @canmengfly, facing a build issue so will have to move the merge tomorrow instead

Sorry about the delay and keep you updated

**Comment by canmengfly** [comment]
Thx，If we can be of help, please do not hesitate to let me know, thanks.

**Comment by canmengfly** [comment]
HI, @pdaryani  Please don't forget the PR here. We are very anxious to resolve it as soon as possible. Thank you.

**Comment by pdaryani** [comment]
Hi @canmengfly  done, it's now live:
https://serverless.com/cn/
https://serverless.com/cn/framework/docs/

While I've made it live (not to delay it any further), the following doc page still needs to be translated to CN (and some links need to be removed since they're not available in CN version): https://serverless.com/cn/framework/docs/providers/tencent/

Could you help me with this please? 

Link to doc source: https://github.com/serverless/serverless/tree/master/docs/cn/providers/tencent

Let me know if you have any other feedback in the meantime :)

**Comment by canmengfly** [comment]
Of course, thank you very much. I will translate and modify the content of the Chinese document tomorrow.

**Comment by pdaryani** [comment]
cheers @canmengfly looking forward to it

**Pull request merged**
