### PR TITLE
Add cn Products pages

### PR DESCRIPTION
**Pull request by yugasun**

### CODE REVIEW

**Comment by ac360** [comment]
Deploy preview for *serverless* processing.

Building with commit 593506633f44abafb126fa1483a5ee55aca8f83c

https://app.netlify.com/sites/serverless/deploys/5e13278923b8450009e1e81d

**Comment by canmengfly** [comment]
HI, @pdaryani  thank you very much for your help. In this PR we have added some pages and it looks very good. But we encountered some problems that could help us remove this popup?

image

**Comment by pdaryani** [comment]
Great stuff @yugasun !  The update is now live: https://serverless.com/cn/cli/

A couple of quick notes:
1 - We use Netlify for hosting and running 'npm run buildprod' with the extended memory command was causing conflict, so I've created 'npm run buildprodlocal' for doing local builds (includes max_old_space_size=4096)

2 - Dropdown menu still points to the English version of `components` and `plugins`, while you've created CN version of both, I notice they don't have Tencent examples yet so assuming that's why you did not include them -- just wanted to double-check that keeping the English version was intentional :)

**Comment by canmengfly** [comment]
@pdaryani @pmuens Excuse me, Can we have a language checkbox for an English website? Removed it here.  :)

**Pull request merged**
