### PR TITLE
feat: add cn learn pages

### PR DESCRIPTION
**Pull request by yugasun**

### CODE REVIEW

**Comment by ac360** [comment]
Deploy preview for *serverless* processing.

Building with commit 1143c1f471a1ca9f5eb71e913e89820064d04e12

https://app.netlify.com/sites/serverless/deploys/5e15ca92062fd9000a164e5c

**Comment by pmuens** [comment]
@yugasun can you please provide some steps how we could test and validate the PR?

I browsed through the Netlify preview but couldn't find the added content.

**Comment by yugasun** [comment]
@pmuens View: https://deploy-preview-522--serverless.netlify.com/cn/, and we update this pages as below link:
image

**Comment by yugasun** [comment]
@pmuens Thanks for your review, could you help to deploy it?

**Pull request merged**
